@WebApi_HostAddress = http://localhost:5180

// Piotr Bacior - WSEI Kraków

GET http://localhost:5180/api/contacts
Accept: application/json

### Dodaj nową osobę (POST)
POST http://localhost:5180/api/contacts/
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Miszal",
  "email": "jan.miszal@example.com",
  "phone": "48 124 466 789",
  "position": "Junior Developer",
  "birthDate": "2005-05-15T00:00:00",
  "gender": 0,
  "address": {
    "street": "ul. Główna 4",
    "city": "Kraków",
    "postalCode": "30-002",
    "country": "Polska",
    "type": 0
  }
}

### Edytuj osobę
PUT http://localhost:5180/api/contacts/022d06a3-dfac-404b-9505-6119b9f40661
Content-Type: application/json

{
  "firstName": "Krzysztof",
  "lastName" : "Kowalski",
  "position": "Senior Developer"
}

### Usuń osobę
DELETE http://localhost:5180/api/contacts/WSTAW_GUID_TUTAJ

### Dodanie notatki do osoby 
POST {{WebApi_HostAddress}}/api/contacts/db0e4aca-71c0-466c-9847-d3dd4ba9b522/notes
Content-Type: application/json

{
  "content": "To jest bardzo ważna notatka dotycząca tej osoby! Oto nasz test PBPB"
}

### Pobierz notatki
GET {{WebApi_HostAddress}}/api/contacts/db0e4aca-71c0-466c-9847-d3dd4ba9b522/notes
Accept: application/json

### Usuń notatkę
DELETE http://localhost:5180/api/contacts/db0e4aca-71c0-466c-9847-d3dd4ba9b522/notes/6ebaa64f-19ef-433c-a14e-41cd7a3906a0
